import jsPDF from 'jspdf';
import { Itinerary } from '../types';

export const generateItineraryPDF = (itinerary: Itinerary): void => {
  const doc = new jsPDF();
  const { tripInput, days } = itinerary;

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.text('Travel Itinerary', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 15;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  const destinationDisplay = tripInput.locations && tripInput.locations.length > 0
    ? tripInput.locations.join(', ')
    : tripInput.country;

  doc.text(`Destination: ${destinationDisplay}`, margin, yPosition);
  yPosition += 7;

  const startDate = new Date(tripInput.startDate).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  const endDate = new Date(tripInput.endDate).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });

  doc.text(`Dates: ${startDate} - ${endDate}`, margin, yPosition);
  yPosition += 7;

  doc.text(
    `Budget: ${tripInput.budget.currencySymbol}${tripInput.budget.min.toLocaleString()} - ${tripInput.budget.currencySymbol}${tripInput.budget.max.toLocaleString()} ${tripInput.budget.currency}`,
    margin,
    yPosition
  );
  yPosition += 7;

  doc.text(`Travel Style: ${tripInput.travelStyle}`, margin, yPosition);
  yPosition += 15;

  days.forEach((day) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235);
    doc.text(`Day ${day.dayNumber} - ${day.date}`, margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);

    doc.setFont('helvetica', 'bold');
    doc.text('Morning (9:00 AM):', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    const morningLines = doc.splitTextToSize(day.morning, pageWidth - 2 * margin);
    doc.text(morningLines, margin, yPosition);
    yPosition += morningLines.length * 5 + 3;

    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Afternoon (2:00 PM):', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    const afternoonLines = doc.splitTextToSize(day.afternoon, pageWidth - 2 * margin);
    doc.text(afternoonLines, margin, yPosition);
    yPosition += afternoonLines.length * 5 + 3;

    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Evening (7:00 PM):', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    const eveningLines = doc.splitTextToSize(day.evening, pageWidth - 2 * margin);
    doc.text(eveningLines, margin, yPosition);
    yPosition += eveningLines.length * 5 + 5;

    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Local Food:', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    const foodLines = doc.splitTextToSize(day.foodSuggestion, pageWidth - 2 * margin);
    doc.text(foodLines, margin, yPosition);
    yPosition += foodLines.length * 5 + 3;

    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Travel Tip:', margin, yPosition);
    yPosition += 5;
    doc.setFont('helvetica', 'normal');

    const tipLines = doc.splitTextToSize(day.travelTip, pageWidth - 2 * margin);
    doc.text(tipLines, margin, yPosition);
    yPosition += tipLines.length * 5 + 10;
  });

  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(
      `Generated by Travel Planner - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  const filename = `itinerary-${destinationDisplay.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`;
  doc.save(filename);
};
